### ISSUE TITLE
lots of similar projects and duplicate effort on npm

### ISSUE THREAD

**Issue by graingert** [alberto-bottarini/google-fonts-downloader#4]
https://npmcompare.com/compare/google-font-installer,google-fonts-downloader,google-fonts-manager,google-fonts-offline,got-google-fonts

**Comment by graingert** [comment]
Here is the issue on multiple projects:

https://github.com/lordgiotto/google-font-installer/issues/6
https://github.com/alberto-bottarini/google-fonts-downloader/issues/4
https://github.com/bali182/google-fonts-manager/issues/1
https://github.com/makovich/google-fonts-offline/issues/4
https://github.com/ragingwind/got-google-fonts/issues/1

**Comment by alberto-bottarini** [comment]
Ok, what's the point?

**Comment by graingert** [comment]
would be much better to work together to create one maintained version and deprecate all the unmaintained versions.

https://xkcd.com/927/

**Comment by alberto-bottarini** [comment]
I know the xkcd strip :)
But these projects aren't web standards. I like to work on my project, with my times, my style, my logic.
